### ISSUE TITLE
LocalJumpError: yield called out of block (JRuby)

### ISSUE THREAD

**Issue by dblock** [rtomayko/tilt#235]
Can someone please help me with https://github.com/LTe/grape-rabl/pull/22 and the failure in https://travis-ci.org/LTe/grape-rabl/jobs/21575957? 

```
1) Grape::Rabl layout default proper render with default layout
     Failure/Error: get("/about")
     LocalJumpError:
       yield called out of block
     # ./spec/views/layout_test/layouts/application.rabl:4:in `(eval)'
     # ./spec/../lib/grape-rabl/formatter.rb:21:in `call'
     # ./spec/../lib/grape-rabl/formatter.rb:50:in `rabl'
     # ./spec/../lib/grape-rabl/formatter.rb:17:in `call'
     # ./spec/grape_rabl_layout_spec.rb:28:in `(root)'
  2) Grape::Rabl layout tilt layout is setup proper render with specified layout
     Failure/Error: get("/about")
     LocalJumpError:
       yield called out of block
     # ./spec/views/layout_test/layouts/another.rabl:2:in `(eval)'
     # ./spec/../lib/grape-rabl/formatter.rb:21:in `call'
     # ./spec/../lib/grape-rabl/formatter.rb:50:in `rabl'
     # ./spec/../lib/grape-rabl/formatter.rb:17:in `call'
     # ./spec/grape_rabl_layout_spec.rb:46:in `(root)'
```

The issue is probably not in tilt, but it's possible.
